/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 83
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 75
#define ALIAS_COUNT 0
#define TOKEN_COUNT 46
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_doctype_token1 = 1,
  aux_sym_doctype_token2 = 2,
  anon_sym_GT = 3,
  anon_sym_LT_BANG_DASH_DASH = 4,
  anon_sym_DASH_DASH_GT = 5,
  sym_comment_text = 6,
  anon_sym_LT = 7,
  anon_sym_area = 8,
  anon_sym_base = 9,
  anon_sym_br = 10,
  anon_sym_col = 11,
  anon_sym_embed = 12,
  anon_sym_hr = 13,
  anon_sym_img = 14,
  anon_sym_input = 15,
  anon_sym_link = 16,
  anon_sym_meta = 17,
  anon_sym_param = 18,
  anon_sym_source = 19,
  anon_sym_track = 20,
  anon_sym_wbr = 21,
  anon_sym_slot = 22,
  anon_sym_window = 23,
  anon_sym_document = 24,
  anon_sym_SLASH_GT = 25,
  anon_sym_LT_SLASH = 26,
  sym_tag_name = 27,
  sym_component_name = 28,
  anon_sym_EQ = 29,
  anon_sym_DOT_DOT_DOT = 30,
  sym_attribute_name = 31,
  sym_event_name = 32,
  anon_sym_DQUOTE = 33,
  sym_attribute_text = 34,
  anon_sym_LBRACE = 35,
  anon_sym_RBRACE = 36,
  aux_sym__expression_chunk_token1 = 37,
  aux_sym__elixir_string_token1 = 38,
  aux_sym__elixir_string_token2 = 39,
  anon_sym_POUND = 40,
  anon_sym_POUND_LBRACE = 41,
  anon_sym_SQUOTE = 42,
  aux_sym__elixir_charlist_token1 = 43,
  sym_escape_sequence = 44,
  sym_text = 45,
  sym_document = 46,
  sym__node = 47,
  sym_doctype = 48,
  sym_comment = 49,
  sym_element = 50,
  sym_void_element = 51,
  sym_start_tag = 52,
  sym_self_closing_tag = 53,
  sym_end_tag = 54,
  sym__tag_name = 55,
  sym_dynamic_tag_name = 56,
  sym__attribute_like = 57,
  sym_attribute = 58,
  sym_event_attribute = 59,
  sym_spread = 60,
  sym__attribute_value = 61,
  sym_quoted_attribute_value = 62,
  sym_expression = 63,
  sym_expression_value = 64,
  sym__expression_chunk = 65,
  sym__elixir_string = 66,
  sym__elixir_charlist = 67,
  aux_sym_document_repeat1 = 68,
  aux_sym_comment_repeat1 = 69,
  aux_sym_void_element_repeat1 = 70,
  aux_sym_quoted_attribute_value_repeat1 = 71,
  aux_sym_expression_value_repeat1 = 72,
  aux_sym__elixir_string_repeat1 = 73,
  aux_sym__elixir_charlist_repeat1 = 74,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_doctype_token1] = "doctype_token1",
  [aux_sym_doctype_token2] = "doctype_token2",
  [anon_sym_GT] = ">",
  [anon_sym_LT_BANG_DASH_DASH] = "<!--",
  [anon_sym_DASH_DASH_GT] = "-->",
  [sym_comment_text] = "comment_text",
  [anon_sym_LT] = "<",
  [anon_sym_area] = "tag_name",
  [anon_sym_base] = "tag_name",
  [anon_sym_br] = "tag_name",
  [anon_sym_col] = "tag_name",
  [anon_sym_embed] = "tag_name",
  [anon_sym_hr] = "tag_name",
  [anon_sym_img] = "tag_name",
  [anon_sym_input] = "tag_name",
  [anon_sym_link] = "tag_name",
  [anon_sym_meta] = "tag_name",
  [anon_sym_param] = "tag_name",
  [anon_sym_source] = "tag_name",
  [anon_sym_track] = "tag_name",
  [anon_sym_wbr] = "tag_name",
  [anon_sym_slot] = "tag_name",
  [anon_sym_window] = "tag_name",
  [anon_sym_document] = "tag_name",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [sym_tag_name] = "tag_name",
  [sym_component_name] = "component_name",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT_DOT_DOT] = "...",
  [sym_attribute_name] = "attribute_name",
  [sym_event_name] = "event_name",
  [anon_sym_DQUOTE] = "\"",
  [sym_attribute_text] = "attribute_text",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym__expression_chunk_token1] = "_expression_chunk_token1",
  [aux_sym__elixir_string_token1] = "_elixir_string_token1",
  [aux_sym__elixir_string_token2] = "_elixir_string_token2",
  [anon_sym_POUND] = "#",
  [anon_sym_POUND_LBRACE] = "#{",
  [anon_sym_SQUOTE] = "'",
  [aux_sym__elixir_charlist_token1] = "_elixir_charlist_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym__node] = "_node",
  [sym_doctype] = "doctype",
  [sym_comment] = "comment",
  [sym_element] = "element",
  [sym_void_element] = "void_element",
  [sym_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym__tag_name] = "_tag_name",
  [sym_dynamic_tag_name] = "dynamic_tag_name",
  [sym__attribute_like] = "_attribute_like",
  [sym_attribute] = "attribute",
  [sym_event_attribute] = "event_attribute",
  [sym_spread] = "spread",
  [sym__attribute_value] = "_attribute_value",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_expression] = "expression",
  [sym_expression_value] = "expression_value",
  [sym__expression_chunk] = "_expression_chunk",
  [sym__elixir_string] = "_elixir_string",
  [sym__elixir_charlist] = "_elixir_charlist",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
  [aux_sym_void_element_repeat1] = "void_element_repeat1",
  [aux_sym_quoted_attribute_value_repeat1] = "quoted_attribute_value_repeat1",
  [aux_sym_expression_value_repeat1] = "expression_value_repeat1",
  [aux_sym__elixir_string_repeat1] = "_elixir_string_repeat1",
  [aux_sym__elixir_charlist_repeat1] = "_elixir_charlist_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [aux_sym_doctype_token2] = aux_sym_doctype_token2,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_BANG_DASH_DASH] = anon_sym_LT_BANG_DASH_DASH,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [sym_comment_text] = sym_comment_text,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_area] = sym_tag_name,
  [anon_sym_base] = sym_tag_name,
  [anon_sym_br] = sym_tag_name,
  [anon_sym_col] = sym_tag_name,
  [anon_sym_embed] = sym_tag_name,
  [anon_sym_hr] = sym_tag_name,
  [anon_sym_img] = sym_tag_name,
  [anon_sym_input] = sym_tag_name,
  [anon_sym_link] = sym_tag_name,
  [anon_sym_meta] = sym_tag_name,
  [anon_sym_param] = sym_tag_name,
  [anon_sym_source] = sym_tag_name,
  [anon_sym_track] = sym_tag_name,
  [anon_sym_wbr] = sym_tag_name,
  [anon_sym_slot] = sym_tag_name,
  [anon_sym_window] = sym_tag_name,
  [anon_sym_document] = sym_tag_name,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [sym_tag_name] = sym_tag_name,
  [sym_component_name] = sym_component_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [sym_attribute_name] = sym_attribute_name,
  [sym_event_name] = sym_event_name,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_attribute_text] = sym_attribute_text,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym__expression_chunk_token1] = aux_sym__expression_chunk_token1,
  [aux_sym__elixir_string_token1] = aux_sym__elixir_string_token1,
  [aux_sym__elixir_string_token2] = aux_sym__elixir_string_token2,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_POUND_LBRACE] = anon_sym_POUND_LBRACE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym__elixir_charlist_token1] = aux_sym__elixir_charlist_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym__node] = sym__node,
  [sym_doctype] = sym_doctype,
  [sym_comment] = sym_comment,
  [sym_element] = sym_element,
  [sym_void_element] = sym_void_element,
  [sym_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym__tag_name] = sym__tag_name,
  [sym_dynamic_tag_name] = sym_dynamic_tag_name,
  [sym__attribute_like] = sym__attribute_like,
  [sym_attribute] = sym_attribute,
  [sym_event_attribute] = sym_event_attribute,
  [sym_spread] = sym_spread,
  [sym__attribute_value] = sym__attribute_value,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_expression] = sym_expression,
  [sym_expression_value] = sym_expression_value,
  [sym__expression_chunk] = sym__expression_chunk,
  [sym__elixir_string] = sym__elixir_string,
  [sym__elixir_charlist] = sym__elixir_charlist,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
  [aux_sym_void_element_repeat1] = aux_sym_void_element_repeat1,
  [aux_sym_quoted_attribute_value_repeat1] = aux_sym_quoted_attribute_value_repeat1,
  [aux_sym_expression_value_repeat1] = aux_sym_expression_value_repeat1,
  [aux_sym__elixir_string_repeat1] = aux_sym__elixir_string_repeat1,
  [aux_sym__elixir_charlist_repeat1] = aux_sym__elixir_charlist_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_doctype_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_BANG_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_comment_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_area] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_base] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_br] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_col] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_embed] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_hr] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_img] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_input] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_link] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_meta] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_param] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_source] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_track] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_wbr] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_slot] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_window] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_document] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_component_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_event_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__expression_chunk_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__elixir_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__elixir_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__elixir_charlist_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_void_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__tag_name] = {
    .visible = false,
    .named = true,
  },
  [sym_dynamic_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__attribute_like] = {
    .visible = false,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_event_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_spread] = {
    .visible = true,
    .named = true,
  },
  [sym__attribute_value] = {
    .visible = false,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_value] = {
    .visible = true,
    .named = true,
  },
  [sym__expression_chunk] = {
    .visible = false,
    .named = true,
  },
  [sym__elixir_string] = {
    .visible = false,
    .named = true,
  },
  [sym__elixir_charlist] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_void_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__elixir_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__elixir_charlist_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 7,
  [13] = 13,
  [14] = 7,
  [15] = 7,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 32,
  [66] = 22,
  [67] = 67,
  [68] = 68,
  [69] = 22,
  [70] = 32,
  [71] = 22,
  [72] = 32,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 75,
  [79] = 79,
  [80] = 75,
  [81] = 81,
  [82] = 75,
};

static const TSCharacterRange sym_attribute_name_character_set_2[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'&', '&'}, {'(', '.'}, {'0', ';'}, {'?', '['}, {']', '_'},
  {'a', 'z'}, {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(28);
      ADVANCE_MAP(
        '"', 116,
        '#', 126,
        '$', 25,
        '\'', 128,
        '-', 9,
        '.', 11,
        '/', 12,
        '<', 38,
        '=', 112,
        '>', 32,
        '\\', 23,
        'a', 97,
        'b', 58,
        'c', 90,
        'd', 91,
        'e', 83,
        'h', 95,
        'i', 84,
        'l', 78,
        'm', 71,
        'p', 63,
        's', 82,
        't', 98,
        'w', 65,
        '{', 119,
        '}', 120,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('f' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(111);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(116);
      if (lookahead == '#') ADVANCE(126);
      if (lookahead == '\\') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(123);
      if (lookahead != 0) ADVANCE(124);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(116);
      if (lookahead == '\'') ADVANCE(128);
      if (lookahead == '{') ADVANCE(119);
      if (lookahead == '}') ADVANCE(120);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(121);
      if (lookahead != 0) ADVANCE(122);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(116);
      if (lookahead == '\\') ADVANCE(23);
      if (lookahead == '{') ADVANCE(119);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(117);
      if (lookahead != 0) ADVANCE(118);
      END_STATE();
    case 4:
      if (lookahead == '$') ADVANCE(25);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == '=') ADVANCE(112);
      if (lookahead == '>') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if ((!eof && set_contains(sym_attribute_name_character_set_2, 11, lookahead))) ADVANCE(114);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(128);
      if (lookahead == '\\') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(129);
      if (lookahead != 0) ADVANCE(130);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(23);
      if (lookahead == '{') ADVANCE(119);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == '.') ADVANCE(113);
      END_STATE();
    case 11:
      if (lookahead == '.') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(56);
      END_STATE();
    case 13:
      if (lookahead == '>') ADVANCE(34);
      END_STATE();
    case 14:
      if (lookahead == '{') ADVANCE(119);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(111);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 15:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 17:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 18:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(20);
      END_STATE();
    case 20:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(18);
      END_STATE();
    case 21:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(132);
      END_STATE();
    case 22:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(31);
      END_STATE();
    case 23:
      if (('"' <= lookahead && lookahead <= '$') ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == '`' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(131);
      END_STATE();
    case 24:
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(111);
      END_STATE();
    case 25:
      if ((!eof && set_contains(sym_attribute_name_character_set_2, 11, lookahead))) ADVANCE(115);
      END_STATE();
    case 26:
      if (lookahead != 0) ADVANCE(125);
      END_STATE();
    case 27:
      if (eof) ADVANCE(28);
      if (lookahead == '<') ADVANCE(38);
      if (lookahead == '\\') ADVANCE(133);
      if (lookahead == '{') ADVANCE(119);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(27);
      if (lookahead != 0) ADVANCE(132);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_doctype_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_doctype_token2);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT_BANG_DASH_DASH);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_comment_text);
      if (lookahead == '-') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_comment_text);
      if (lookahead == '-') ADVANCE(13);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_comment_text);
      if (lookahead != 0 &&
          lookahead != '-' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(8);
      if (lookahead == '/') ADVANCE(57);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_area);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_base);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_br);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_col);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_embed);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_hr);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_img);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_input);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_link);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_meta);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_param);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_source);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_track);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_wbr);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_slot);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_window);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_document);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'a') ADVANCE(101);
      if (lookahead == 'r') ADVANCE(41);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'a') ADVANCE(39);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'a') ADVANCE(48);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'a') ADVANCE(67);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'a') ADVANCE(85);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'a') ADVANCE(100);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'b') ADVANCE(74);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'b') ADVANCE(96);
      if (lookahead == 'i') ADVANCE(88);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'c') ADVANCE(106);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'c') ADVANCE(80);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'c') ADVANCE(73);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'd') ADVANCE(43);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'd') ADVANCE(92);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'e') ADVANCE(105);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'e') ADVANCE(40);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'e') ADVANCE(50);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'e') ADVANCE(69);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'e') ADVANCE(59);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'e') ADVANCE(89);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'g') ADVANCE(45);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'i') ADVANCE(87);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'k') ADVANCE(47);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'k') ADVANCE(51);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'l') ADVANCE(42);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'l') ADVANCE(93);
      if (lookahead == 'o') ADVANCE(108);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'm') ADVANCE(64);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'm') ADVANCE(77);
      if (lookahead == 'n') ADVANCE(94);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'm') ADVANCE(49);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'm') ADVANCE(76);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'n') ADVANCE(79);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'n') ADVANCE(70);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'n') ADVANCE(104);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'o') ADVANCE(81);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'o') ADVANCE(66);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'o') ADVANCE(109);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'o') ADVANCE(102);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'p') ADVANCE(107);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(44);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(52);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(75);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(61);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(68);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'r') ADVANCE(62);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 's') ADVANCE(72);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 't') ADVANCE(53);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 't') ADVANCE(46);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 't') ADVANCE(55);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 't') ADVANCE(60);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'u') ADVANCE(86);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'u') ADVANCE(103);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'u') ADVANCE(99);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'w') ADVANCE(54);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(110);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_component_name);
      if (lookahead == '.') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(111);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_attribute_name);
      if ((!eof && set_contains(sym_attribute_name_character_set_2, 11, lookahead))) ADVANCE(114);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_event_name);
      if ((!eof && set_contains(sym_attribute_name_character_set_2, 11, lookahead))) ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_attribute_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(118);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_attribute_text);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(118);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym__expression_chunk_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(122);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym__expression_chunk_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(122);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(aux_sym__elixir_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(123);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(124);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(aux_sym__elixir_string_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(124);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(aux_sym__elixir_string_token2);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '{') ADVANCE(127);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_POUND_LBRACE);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(aux_sym__elixir_charlist_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(130);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(aux_sym__elixir_charlist_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(130);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(132);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_text);
      if (('"' <= lookahead && lookahead <= '$') ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == '`' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(131);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 27},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 27},
  [4] = {.lex_state = 27},
  [5] = {.lex_state = 27},
  [6] = {.lex_state = 27},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 27},
  [23] = {.lex_state = 27},
  [24] = {.lex_state = 27},
  [25] = {.lex_state = 27},
  [26] = {.lex_state = 27},
  [27] = {.lex_state = 27},
  [28] = {.lex_state = 27},
  [29] = {.lex_state = 27},
  [30] = {.lex_state = 27},
  [31] = {.lex_state = 27},
  [32] = {.lex_state = 27},
  [33] = {.lex_state = 27},
  [34] = {.lex_state = 27},
  [35] = {.lex_state = 27},
  [36] = {.lex_state = 27},
  [37] = {.lex_state = 14},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 7},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 4},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 4},
  [67] = {.lex_state = 5},
  [68] = {.lex_state = 5},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 7},
  [71] = {.lex_state = 7},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 5},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 22},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_doctype_token1] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(1),
    [anon_sym_DASH_DASH_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_area] = ACTIONS(1),
    [anon_sym_base] = ACTIONS(1),
    [anon_sym_br] = ACTIONS(1),
    [anon_sym_col] = ACTIONS(1),
    [anon_sym_embed] = ACTIONS(1),
    [anon_sym_hr] = ACTIONS(1),
    [anon_sym_img] = ACTIONS(1),
    [anon_sym_input] = ACTIONS(1),
    [anon_sym_link] = ACTIONS(1),
    [anon_sym_meta] = ACTIONS(1),
    [anon_sym_param] = ACTIONS(1),
    [anon_sym_source] = ACTIONS(1),
    [anon_sym_track] = ACTIONS(1),
    [anon_sym_wbr] = ACTIONS(1),
    [anon_sym_slot] = ACTIONS(1),
    [anon_sym_window] = ACTIONS(1),
    [anon_sym_document] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
    [sym_component_name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [sym_event_name] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_POUND_LBRACE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(76),
    [sym__node] = STATE(6),
    [sym_doctype] = STATE(6),
    [sym_comment] = STATE(6),
    [sym_element] = STATE(6),
    [sym_void_element] = STATE(6),
    [sym_start_tag] = STATE(3),
    [sym_self_closing_tag] = STATE(29),
    [sym_expression] = STATE(6),
    [aux_sym_document_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_doctype_token1] = ACTIONS(5),
    [anon_sym_LT_BANG_DASH_DASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [sym_escape_sequence] = ACTIONS(13),
    [sym_text] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(19), 1,
      sym_tag_name,
    ACTIONS(21), 1,
      sym_component_name,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    STATE(50), 1,
      sym_expression,
    STATE(9), 2,
      sym__tag_name,
      sym_dynamic_tag_name,
    ACTIONS(17), 17,
      anon_sym_area,
      anon_sym_base,
      anon_sym_br,
      anon_sym_col,
      anon_sym_embed,
      anon_sym_hr,
      anon_sym_img,
      anon_sym_input,
      anon_sym_link,
      anon_sym_meta,
      anon_sym_param,
      anon_sym_source,
      anon_sym_track,
      anon_sym_wbr,
      anon_sym_slot,
      anon_sym_window,
      anon_sym_document,
  [36] = 11,
    ACTIONS(5), 1,
      aux_sym_doctype_token1,
    ACTIONS(7), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(27), 1,
      sym_escape_sequence,
    ACTIONS(29), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(34), 1,
      sym_end_tag,
    STATE(4), 7,
      sym__node,
      sym_doctype,
      sym_comment,
      sym_element,
      sym_void_element,
      sym_expression,
      aux_sym_document_repeat1,
  [76] = 11,
    ACTIONS(5), 1,
      aux_sym_doctype_token1,
    ACTIONS(7), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(31), 1,
      sym_escape_sequence,
    ACTIONS(33), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(30), 1,
      sym_end_tag,
    STATE(5), 7,
      sym__node,
      sym_doctype,
      sym_comment,
      sym_element,
      sym_void_element,
      sym_expression,
      aux_sym_document_repeat1,
  [116] = 10,
    ACTIONS(37), 1,
      aux_sym_doctype_token1,
    ACTIONS(40), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(46), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      sym_escape_sequence,
    ACTIONS(52), 1,
      sym_text,
    STATE(3), 1,
      sym_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    ACTIONS(35), 2,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
    STATE(5), 7,
      sym__node,
      sym_doctype,
      sym_comment,
      sym_element,
      sym_void_element,
      sym_expression,
      aux_sym_document_repeat1,
  [154] = 10,
    ACTIONS(5), 1,
      aux_sym_doctype_token1,
    ACTIONS(7), 1,
      anon_sym_LT_BANG_DASH_DASH,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_escape_sequence,
    ACTIONS(33), 1,
      sym_text,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(5), 7,
      sym__node,
      sym_doctype,
      sym_comment,
      sym_element,
      sym_void_element,
      sym_expression,
      aux_sym_document_repeat1,
  [191] = 7,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    ACTIONS(63), 1,
      aux_sym__expression_chunk_token1,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    STATE(75), 1,
      sym_expression_value,
    STATE(17), 4,
      sym__expression_chunk,
      sym__elixir_string,
      sym__elixir_charlist,
      aux_sym_expression_value_repeat1,
  [216] = 5,
    ACTIONS(69), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(71), 1,
      sym_attribute_name,
    ACTIONS(73), 1,
      sym_event_name,
    ACTIONS(67), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(11), 5,
      sym__attribute_like,
      sym_attribute,
      sym_event_attribute,
      sym_spread,
      aux_sym_void_element_repeat1,
  [237] = 6,
    ACTIONS(69), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(71), 1,
      sym_attribute_name,
    ACTIONS(73), 1,
      sym_event_name,
    ACTIONS(75), 1,
      anon_sym_GT,
    ACTIONS(77), 1,
      anon_sym_SLASH_GT,
    STATE(10), 5,
      sym__attribute_like,
      sym_attribute,
      sym_event_attribute,
      sym_spread,
      aux_sym_void_element_repeat1,
  [260] = 6,
    ACTIONS(69), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(71), 1,
      sym_attribute_name,
    ACTIONS(73), 1,
      sym_event_name,
    ACTIONS(79), 1,
      anon_sym_GT,
    ACTIONS(81), 1,
      anon_sym_SLASH_GT,
    STATE(13), 5,
      sym__attribute_like,
      sym_attribute,
      sym_event_attribute,
      sym_spread,
      aux_sym_void_element_repeat1,
  [283] = 5,
    ACTIONS(69), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(71), 1,
      sym_attribute_name,
    ACTIONS(73), 1,
      sym_event_name,
    ACTIONS(83), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(13), 5,
      sym__attribute_like,
      sym_attribute,
      sym_event_attribute,
      sym_spread,
      aux_sym_void_element_repeat1,
  [304] = 7,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      aux_sym__expression_chunk_token1,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
    STATE(78), 1,
      sym_expression_value,
    STATE(17), 4,
      sym__expression_chunk,
      sym__elixir_string,
      sym__elixir_charlist,
      aux_sym_expression_value_repeat1,
  [329] = 5,
    ACTIONS(89), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(92), 1,
      sym_attribute_name,
    ACTIONS(95), 1,
      sym_event_name,
    ACTIONS(87), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(13), 5,
      sym__attribute_like,
      sym_attribute,
      sym_event_attribute,
      sym_spread,
      aux_sym_void_element_repeat1,
  [350] = 7,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      aux_sym__expression_chunk_token1,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(98), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_expression_value,
    STATE(17), 4,
      sym__expression_chunk,
      sym__elixir_string,
      sym__elixir_charlist,
      aux_sym_expression_value_repeat1,
  [375] = 7,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      aux_sym__expression_chunk_token1,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_expression_value,
    STATE(17), 4,
      sym__expression_chunk,
      sym__elixir_string,
      sym__elixir_charlist,
      aux_sym_expression_value_repeat1,
  [400] = 6,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    ACTIONS(104), 1,
      aux_sym__expression_chunk_token1,
    STATE(21), 4,
      sym__expression_chunk,
      sym__elixir_string,
      sym__elixir_charlist,
      aux_sym_expression_value_repeat1,
  [422] = 6,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    ACTIONS(108), 1,
      aux_sym__expression_chunk_token1,
    STATE(19), 4,
      sym__expression_chunk,
      sym__elixir_string,
      sym__elixir_charlist,
      aux_sym_expression_value_repeat1,
  [444] = 6,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    ACTIONS(112), 1,
      aux_sym__expression_chunk_token1,
    STATE(20), 4,
      sym__expression_chunk,
      sym__elixir_string,
      sym__elixir_charlist,
      aux_sym_expression_value_repeat1,
  [466] = 6,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(117), 1,
      anon_sym_LBRACE,
    ACTIONS(120), 1,
      anon_sym_RBRACE,
    ACTIONS(122), 1,
      aux_sym__expression_chunk_token1,
    ACTIONS(125), 1,
      anon_sym_SQUOTE,
    STATE(19), 4,
      sym__expression_chunk,
      sym__elixir_string,
      sym__elixir_charlist,
      aux_sym_expression_value_repeat1,
  [488] = 6,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(108), 1,
      aux_sym__expression_chunk_token1,
    ACTIONS(128), 1,
      anon_sym_RBRACE,
    STATE(19), 4,
      sym__expression_chunk,
      sym__elixir_string,
      sym__elixir_charlist,
      aux_sym_expression_value_repeat1,
  [510] = 6,
    ACTIONS(57), 1,
      anon_sym_DQUOTE,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(65), 1,
      anon_sym_SQUOTE,
    ACTIONS(108), 1,
      aux_sym__expression_chunk_token1,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
    STATE(19), 4,
      sym__expression_chunk,
      sym__elixir_string,
      sym__elixir_charlist,
      aux_sym_expression_value_repeat1,
  [532] = 2,
    ACTIONS(134), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(132), 6,
      ts_builtin_sym_end,
      aux_sym_doctype_token1,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [545] = 2,
    ACTIONS(138), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(136), 6,
      ts_builtin_sym_end,
      aux_sym_doctype_token1,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [558] = 2,
    ACTIONS(142), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(140), 6,
      ts_builtin_sym_end,
      aux_sym_doctype_token1,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [571] = 2,
    ACTIONS(146), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(144), 6,
      ts_builtin_sym_end,
      aux_sym_doctype_token1,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [584] = 2,
    ACTIONS(150), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(148), 6,
      ts_builtin_sym_end,
      aux_sym_doctype_token1,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [597] = 2,
    ACTIONS(154), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(152), 6,
      ts_builtin_sym_end,
      aux_sym_doctype_token1,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [610] = 2,
    ACTIONS(158), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(156), 6,
      ts_builtin_sym_end,
      aux_sym_doctype_token1,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [623] = 2,
    ACTIONS(162), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(160), 6,
      ts_builtin_sym_end,
      aux_sym_doctype_token1,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [636] = 2,
    ACTIONS(166), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(164), 6,
      ts_builtin_sym_end,
      aux_sym_doctype_token1,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [649] = 2,
    ACTIONS(170), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(168), 6,
      ts_builtin_sym_end,
      aux_sym_doctype_token1,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [662] = 2,
    ACTIONS(174), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(172), 6,
      ts_builtin_sym_end,
      aux_sym_doctype_token1,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [675] = 2,
    ACTIONS(178), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(176), 6,
      ts_builtin_sym_end,
      aux_sym_doctype_token1,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [688] = 2,
    ACTIONS(182), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(180), 6,
      ts_builtin_sym_end,
      aux_sym_doctype_token1,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [701] = 2,
    ACTIONS(186), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(184), 5,
      aux_sym_doctype_token1,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [713] = 2,
    ACTIONS(190), 2,
      anon_sym_LT,
      sym_text,
    ACTIONS(188), 5,
      aux_sym_doctype_token1,
      anon_sym_LT_BANG_DASH_DASH,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [725] = 4,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    STATE(50), 1,
      sym_expression,
    ACTIONS(192), 2,
      sym_tag_name,
      sym_component_name,
    STATE(81), 2,
      sym__tag_name,
      sym_dynamic_tag_name,
  [740] = 4,
    ACTIONS(194), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(198), 1,
      anon_sym_LBRACE,
    ACTIONS(196), 2,
      sym_comment_text,
      sym_escape_sequence,
    STATE(42), 2,
      sym_expression,
      aux_sym_comment_repeat1,
  [755] = 5,
    ACTIONS(200), 1,
      anon_sym_DQUOTE,
    ACTIONS(202), 1,
      aux_sym__elixir_string_token1,
    ACTIONS(206), 1,
      anon_sym_POUND_LBRACE,
    STATE(43), 1,
      aux_sym__elixir_string_repeat1,
    ACTIONS(204), 2,
      aux_sym__elixir_string_token2,
      anon_sym_POUND,
  [772] = 2,
    ACTIONS(210), 1,
      anon_sym_EQ,
    ACTIONS(208), 5,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_DOT_DOT_DOT,
      sym_attribute_name,
      sym_event_name,
  [783] = 2,
    ACTIONS(214), 1,
      anon_sym_EQ,
    ACTIONS(212), 5,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_DOT_DOT_DOT,
      sym_attribute_name,
      sym_event_name,
  [794] = 4,
    ACTIONS(198), 1,
      anon_sym_LBRACE,
    ACTIONS(216), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(218), 2,
      sym_comment_text,
      sym_escape_sequence,
    STATE(45), 2,
      sym_expression,
      aux_sym_comment_repeat1,
  [809] = 5,
    ACTIONS(206), 1,
      anon_sym_POUND_LBRACE,
    ACTIONS(220), 1,
      anon_sym_DQUOTE,
    ACTIONS(222), 1,
      aux_sym__elixir_string_token1,
    STATE(44), 1,
      aux_sym__elixir_string_repeat1,
    ACTIONS(224), 2,
      aux_sym__elixir_string_token2,
      anon_sym_POUND,
  [826] = 5,
    ACTIONS(226), 1,
      anon_sym_DQUOTE,
    ACTIONS(228), 1,
      aux_sym__elixir_string_token1,
    ACTIONS(234), 1,
      anon_sym_POUND_LBRACE,
    STATE(44), 1,
      aux_sym__elixir_string_repeat1,
    ACTIONS(231), 2,
      aux_sym__elixir_string_token2,
      anon_sym_POUND,
  [843] = 4,
    ACTIONS(237), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(242), 1,
      anon_sym_LBRACE,
    ACTIONS(239), 2,
      sym_comment_text,
      sym_escape_sequence,
    STATE(45), 2,
      sym_expression,
      aux_sym_comment_repeat1,
  [858] = 5,
    ACTIONS(245), 1,
      anon_sym_DQUOTE,
    ACTIONS(247), 1,
      sym_attribute_text,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
    ACTIONS(251), 1,
      sym_escape_sequence,
    STATE(47), 2,
      sym_expression,
      aux_sym_quoted_attribute_value_repeat1,
  [875] = 5,
    ACTIONS(249), 1,
      anon_sym_LBRACE,
    ACTIONS(253), 1,
      anon_sym_DQUOTE,
    ACTIONS(255), 1,
      sym_attribute_text,
    ACTIONS(257), 1,
      sym_escape_sequence,
    STATE(48), 2,
      sym_expression,
      aux_sym_quoted_attribute_value_repeat1,
  [892] = 5,
    ACTIONS(259), 1,
      anon_sym_DQUOTE,
    ACTIONS(261), 1,
      sym_attribute_text,
    ACTIONS(264), 1,
      anon_sym_LBRACE,
    ACTIONS(267), 1,
      sym_escape_sequence,
    STATE(48), 2,
      sym_expression,
      aux_sym_quoted_attribute_value_repeat1,
  [909] = 2,
    ACTIONS(272), 1,
      aux_sym__expression_chunk_token1,
    ACTIONS(270), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
  [919] = 1,
    ACTIONS(274), 5,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_DOT_DOT_DOT,
      sym_attribute_name,
      sym_event_name,
  [927] = 2,
    ACTIONS(278), 1,
      aux_sym__expression_chunk_token1,
    ACTIONS(276), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
  [937] = 2,
    ACTIONS(280), 1,
      aux_sym__elixir_string_token1,
    ACTIONS(226), 4,
      anon_sym_DQUOTE,
      aux_sym__elixir_string_token2,
      anon_sym_POUND,
      anon_sym_POUND_LBRACE,
  [947] = 2,
    ACTIONS(284), 1,
      aux_sym__expression_chunk_token1,
    ACTIONS(282), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
  [957] = 2,
    ACTIONS(288), 1,
      aux_sym__expression_chunk_token1,
    ACTIONS(286), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
  [967] = 1,
    ACTIONS(290), 5,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_DOT_DOT_DOT,
      sym_attribute_name,
      sym_event_name,
  [975] = 2,
    ACTIONS(294), 1,
      aux_sym__expression_chunk_token1,
    ACTIONS(292), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
  [985] = 3,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(296), 1,
      anon_sym_DQUOTE,
    STATE(59), 3,
      sym__attribute_value,
      sym_quoted_attribute_value,
      sym_expression,
  [997] = 3,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(296), 1,
      anon_sym_DQUOTE,
    STATE(60), 3,
      sym__attribute_value,
      sym_quoted_attribute_value,
      sym_expression,
  [1009] = 1,
    ACTIONS(298), 5,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_DOT_DOT_DOT,
      sym_attribute_name,
      sym_event_name,
  [1017] = 1,
    ACTIONS(300), 5,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_DOT_DOT_DOT,
      sym_attribute_name,
      sym_event_name,
  [1025] = 2,
    ACTIONS(304), 1,
      aux_sym__elixir_string_token1,
    ACTIONS(302), 4,
      anon_sym_DQUOTE,
      aux_sym__elixir_string_token2,
      anon_sym_POUND,
      anon_sym_POUND_LBRACE,
  [1035] = 1,
    ACTIONS(306), 5,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_DOT_DOT_DOT,
      sym_attribute_name,
      sym_event_name,
  [1043] = 2,
    ACTIONS(310), 1,
      aux_sym__expression_chunk_token1,
    ACTIONS(308), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
  [1053] = 1,
    ACTIONS(312), 5,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_DOT_DOT_DOT,
      sym_attribute_name,
      sym_event_name,
  [1061] = 1,
    ACTIONS(172), 5,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_DOT_DOT_DOT,
      sym_attribute_name,
      sym_event_name,
  [1069] = 1,
    ACTIONS(132), 5,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      anon_sym_DOT_DOT_DOT,
      sym_attribute_name,
      sym_event_name,
  [1077] = 4,
    ACTIONS(314), 1,
      aux_sym__elixir_string_token2,
    ACTIONS(316), 1,
      anon_sym_SQUOTE,
    ACTIONS(318), 1,
      aux_sym__elixir_charlist_token1,
    STATE(73), 1,
      aux_sym__elixir_charlist_repeat1,
  [1090] = 4,
    ACTIONS(320), 1,
      aux_sym__elixir_string_token2,
    ACTIONS(323), 1,
      anon_sym_SQUOTE,
    ACTIONS(325), 1,
      aux_sym__elixir_charlist_token1,
    STATE(68), 1,
      aux_sym__elixir_charlist_repeat1,
  [1103] = 2,
    ACTIONS(132), 1,
      sym_attribute_text,
    ACTIONS(134), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [1112] = 1,
    ACTIONS(174), 4,
      anon_sym_DASH_DASH_GT,
      sym_comment_text,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [1119] = 1,
    ACTIONS(134), 4,
      anon_sym_DASH_DASH_GT,
      sym_comment_text,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [1126] = 2,
    ACTIONS(172), 1,
      sym_attribute_text,
    ACTIONS(174), 3,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
      sym_escape_sequence,
  [1135] = 4,
    ACTIONS(328), 1,
      aux_sym__elixir_string_token2,
    ACTIONS(330), 1,
      anon_sym_SQUOTE,
    ACTIONS(332), 1,
      aux_sym__elixir_charlist_token1,
    STATE(68), 1,
      aux_sym__elixir_charlist_repeat1,
  [1148] = 2,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    STATE(55), 1,
      sym_expression,
  [1155] = 1,
    ACTIONS(334), 1,
      anon_sym_RBRACE,
  [1159] = 1,
    ACTIONS(336), 1,
      ts_builtin_sym_end,
  [1163] = 1,
    ACTIONS(338), 1,
      anon_sym_GT,
  [1167] = 1,
    ACTIONS(340), 1,
      anon_sym_RBRACE,
  [1171] = 1,
    ACTIONS(342), 1,
      aux_sym_doctype_token2,
  [1175] = 1,
    ACTIONS(344), 1,
      anon_sym_RBRACE,
  [1179] = 1,
    ACTIONS(346), 1,
      anon_sym_GT,
  [1183] = 1,
    ACTIONS(348), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 76,
  [SMALL_STATE(5)] = 116,
  [SMALL_STATE(6)] = 154,
  [SMALL_STATE(7)] = 191,
  [SMALL_STATE(8)] = 216,
  [SMALL_STATE(9)] = 237,
  [SMALL_STATE(10)] = 260,
  [SMALL_STATE(11)] = 283,
  [SMALL_STATE(12)] = 304,
  [SMALL_STATE(13)] = 329,
  [SMALL_STATE(14)] = 350,
  [SMALL_STATE(15)] = 375,
  [SMALL_STATE(16)] = 400,
  [SMALL_STATE(17)] = 422,
  [SMALL_STATE(18)] = 444,
  [SMALL_STATE(19)] = 466,
  [SMALL_STATE(20)] = 488,
  [SMALL_STATE(21)] = 510,
  [SMALL_STATE(22)] = 532,
  [SMALL_STATE(23)] = 545,
  [SMALL_STATE(24)] = 558,
  [SMALL_STATE(25)] = 571,
  [SMALL_STATE(26)] = 584,
  [SMALL_STATE(27)] = 597,
  [SMALL_STATE(28)] = 610,
  [SMALL_STATE(29)] = 623,
  [SMALL_STATE(30)] = 636,
  [SMALL_STATE(31)] = 649,
  [SMALL_STATE(32)] = 662,
  [SMALL_STATE(33)] = 675,
  [SMALL_STATE(34)] = 688,
  [SMALL_STATE(35)] = 701,
  [SMALL_STATE(36)] = 713,
  [SMALL_STATE(37)] = 725,
  [SMALL_STATE(38)] = 740,
  [SMALL_STATE(39)] = 755,
  [SMALL_STATE(40)] = 772,
  [SMALL_STATE(41)] = 783,
  [SMALL_STATE(42)] = 794,
  [SMALL_STATE(43)] = 809,
  [SMALL_STATE(44)] = 826,
  [SMALL_STATE(45)] = 843,
  [SMALL_STATE(46)] = 858,
  [SMALL_STATE(47)] = 875,
  [SMALL_STATE(48)] = 892,
  [SMALL_STATE(49)] = 909,
  [SMALL_STATE(50)] = 919,
  [SMALL_STATE(51)] = 927,
  [SMALL_STATE(52)] = 937,
  [SMALL_STATE(53)] = 947,
  [SMALL_STATE(54)] = 957,
  [SMALL_STATE(55)] = 967,
  [SMALL_STATE(56)] = 975,
  [SMALL_STATE(57)] = 985,
  [SMALL_STATE(58)] = 997,
  [SMALL_STATE(59)] = 1009,
  [SMALL_STATE(60)] = 1017,
  [SMALL_STATE(61)] = 1025,
  [SMALL_STATE(62)] = 1035,
  [SMALL_STATE(63)] = 1043,
  [SMALL_STATE(64)] = 1053,
  [SMALL_STATE(65)] = 1061,
  [SMALL_STATE(66)] = 1069,
  [SMALL_STATE(67)] = 1077,
  [SMALL_STATE(68)] = 1090,
  [SMALL_STATE(69)] = 1103,
  [SMALL_STATE(70)] = 1112,
  [SMALL_STATE(71)] = 1119,
  [SMALL_STATE(72)] = 1126,
  [SMALL_STATE(73)] = 1135,
  [SMALL_STATE(74)] = 1148,
  [SMALL_STATE(75)] = 1155,
  [SMALL_STATE(76)] = 1159,
  [SMALL_STATE(77)] = 1163,
  [SMALL_STATE(78)] = 1167,
  [SMALL_STATE(79)] = 1171,
  [SMALL_STATE(80)] = 1175,
  [SMALL_STATE(81)] = 1179,
  [SMALL_STATE(82)] = 1183,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_void_element_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_void_element_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_void_element_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_void_element_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_value, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_value_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_value_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_value_repeat1, 2, 0, 0),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_value_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [125] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_value_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_void_element, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_void_element, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_void_element, 4, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_void_element, 4, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_event_attribute, 1, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__elixir_string_repeat1, 2, 0, 0),
  [228] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elixir_string_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [231] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__elixir_string_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [234] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__elixir_string_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [239] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [242] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0),
  [261] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [264] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [267] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__elixir_string, 3, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__elixir_string, 3, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dynamic_tag_name, 1, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression_chunk, 2, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression_chunk, 2, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__elixir_string_repeat1, 2, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression_chunk, 3, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression_chunk, 3, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__elixir_string, 2, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__elixir_string, 2, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spread, 2, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__elixir_charlist, 3, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__elixir_charlist, 3, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_event_attribute, 3, 0, 0),
  [302] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__elixir_string_repeat1, 3, 0, 0),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__elixir_string_repeat1, 3, 0, 0),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [308] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__elixir_charlist, 2, 0, 0),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__elixir_charlist, 2, 0, 0),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [314] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [316] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [320] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__elixir_charlist_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [323] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__elixir_charlist_repeat1, 2, 0, 0),
  [325] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__elixir_charlist_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [328] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [330] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [336] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_holo(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "holo",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
